// Static mock data used during development and UI prototyping.
// In production these are replaced by live API responses from the backend.

import { Category, Provider, Review, User } from "@/types";

// Eight service categories covering the main home-service verticals.
// The `icon` string maps to a Lucide component in CategoryCard.
export const CATEGORIES: Category[] = [
  {
    id: "cat_1",
    name: "AC Repair",
    icon: "AirVent",
    description: "Air conditioning installation, maintenance & repair",
    providerCount: 24,
  },
  {
    id: "cat_2",
    name: "Plumbing",
    icon: "Droplets",
    description: "Pipe repairs, leaks, installations & drainage",
    providerCount: 31,
  },
  {
    id: "cat_3",
    name: "Electrician",
    icon: "Zap",
    description: "Wiring, fixtures, panels & electrical repairs",
    providerCount: 28,
  },
  {
    id: "cat_4",
    name: "Laundry",
    icon: "WashingMachine",
    description: "Wash, dry, iron & fold services",
    providerCount: 17,
  },
  {
    id: "cat_5",
    name: "Cleaning",
    icon: "Sparkles",
    description: "Home & office deep cleaning services",
    providerCount: 42,
  },
  {
    id: "cat_6",
    name: "Painting",
    icon: "PaintBucket",
    description: "Interior & exterior painting services",
    providerCount: 19,
  },
  {
    id: "cat_7",
    name: "Carpentry",
    icon: "Hammer",
    description: "Furniture repair, installation & custom woodwork",
    providerCount: 14,
  },
  {
    id: "cat_8",
    name: "Pest Control",
    icon: "Bug",
    description: "Termite, rodent & insect control services",
    providerCount: 12,
  },
];

// Six sample provider profiles covering different categories and verification states.
// Images are sourced from Unsplash (publicly accessible, no auth required).
export const PROVIDERS: Provider[] = [
  {
    id: "prov_1",
    userId: "user_10",
    businessName: "CoolBreeze AC Services",
    categoryId: "cat_1",
    categoryName: "AC Repair",
    location: "Downtown, New York",
    rating: 4.8,
    reviewCount: 127,
    verified: true,
    bio: "10+ years of experience in AC installation, maintenance and repair. We service all major brands including Carrier, Daikin, LG, Samsung, and more. Available 7 days a week.",
    experience: "10 years",
    availability: "Mon–Sun, 8am–8pm",
    phone: "+1 (555) 100-2001",
    email: "coolbreeze@example.com",
    images: [
      "https://images.unsplash.com/photo-1581093450021-4a7360e9a6b5?w=800&q=80",
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    ],
    services: [
      { id: "s1", name: "AC Installation", description: "Full unit setup", price: 120, unit: "per unit", duration: "3–4 hrs" },
      { id: "s2", name: "AC Servicing", description: "Cleaning & maintenance", price: 45, unit: "per visit", duration: "1–2 hrs" },
      { id: "s3", name: "AC Repair", description: "Diagnosis & fix", price: 60, unit: "starting", duration: "2–3 hrs" },
      { id: "s4", name: "Gas Refill", description: "Refrigerant top-up", price: 80, unit: "per unit", duration: "1 hr" },
    ],
    createdAt: "2023-03-15",
  },
  {
    id: "prov_2",
    userId: "user_11",
    businessName: "QuickFix Plumbing",
    categoryId: "cat_2",
    categoryName: "Plumbing",
    location: "Brooklyn, New York",
    rating: 4.6,
    reviewCount: 89,
    verified: true,
    bio: "Licensed plumbers available 24/7 for emergencies. We handle everything from dripping faucets to full pipe replacements. Transparent pricing, no hidden fees.",
    experience: "8 years",
    availability: "24/7 Emergency",
    phone: "+1 (555) 100-2002",
    email: "quickfix@example.com",
    images: [
      "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=800&q=80",
    ],
    services: [
      { id: "s5", name: "Leak Repair", description: "Fix pipe & faucet leaks", price: 40, unit: "starting", duration: "30–60 min" },
      { id: "s6", name: "Drain Cleaning", description: "Unclog drains", price: 55, unit: "per drain", duration: "1 hr" },
      { id: "s7", name: "Water Heater Install", description: "New unit installation", price: 200, unit: "per unit", duration: "4–5 hrs" },
      { id: "s8", name: "Full Inspection", description: "Comprehensive check", price: 80, unit: "per visit", duration: "2 hrs" },
    ],
    createdAt: "2023-06-01",
  },
  {
    id: "prov_3",
    userId: "user_12",
    businessName: "Spark Electric Co.",
    categoryId: "cat_3",
    categoryName: "Electrician",
    location: "Queens, New York",
    rating: 4.9,
    reviewCount: 203,
    verified: true,
    bio: "Certified master electricians. Residential and commercial electrical work. We prioritize safety and code compliance on every job.",
    experience: "15 years",
    availability: "Mon–Sat, 7am–7pm",
    phone: "+1 (555) 100-2003",
    email: "spark@example.com",
    images: [
      "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=800&q=80",
    ],
    services: [
      { id: "s9", name: "Wiring & Rewiring", description: "New or updated wiring", price: 90, unit: "per hour", duration: "varies" },
      { id: "s10", name: "Panel Upgrade", description: "Electrical panel service", price: 350, unit: "starting", duration: "4–6 hrs" },
      { id: "s11", name: "Outlet Installation", description: "Add new outlets", price: 50, unit: "per outlet", duration: "30 min" },
      { id: "s12", name: "Lighting Setup", description: "Fixture install & repair", price: 65, unit: "per fixture", duration: "1 hr" },
    ],
    createdAt: "2022-11-20",
  },
  {
    id: "prov_4",
    userId: "user_13",
    businessName: "Fresh Laundry Hub",
    categoryId: "cat_4",
    categoryName: "Laundry",
    location: "Manhattan, New York",
    rating: 4.5,
    reviewCount: 56,
    // Not yet verified — shown as "Pending" in the admin panel
    verified: false,
    bio: "Same-day pickup and delivery laundry service. We use eco-friendly detergents and handle your clothes with care.",
    experience: "4 years",
    availability: "Mon–Sat, 9am–6pm",
    phone: "+1 (555) 100-2004",
    email: "freshlaundry@example.com",
    images: [],
    services: [
      { id: "s13", name: "Wash & Fold", description: "Per pound service", price: 2, unit: "per lb", duration: "Same day" },
      { id: "s14", name: "Dry Cleaning", description: "Delicate garments", price: 8, unit: "per item", duration: "2 days" },
      { id: "s15", name: "Ironing", description: "Press & fold", price: 3, unit: "per item", duration: "Same day" },
    ],
    createdAt: "2024-01-10",
  },
  {
    id: "prov_5",
    userId: "user_14",
    businessName: "ShineHome Cleaning",
    categoryId: "cat_5",
    categoryName: "Cleaning",
    location: "Bronx, New York",
    rating: 4.7,
    reviewCount: 144,
    verified: true,
    bio: "Professional home and office cleaning using eco-certified products. Flexible scheduling, insured team.",
    experience: "6 years",
    availability: "Mon–Sun, 8am–5pm",
    phone: "+1 (555) 100-2005",
    email: "shinehome@example.com",
    images: [
      "https://images.unsplash.com/photo-1527515545081-5db817172677?w=800&q=80",
    ],
    services: [
      { id: "s16", name: "Standard Cleaning", description: "Regular home clean", price: 80, unit: "per session", duration: "2–3 hrs" },
      { id: "s17", name: "Deep Cleaning", description: "Thorough full clean", price: 150, unit: "per session", duration: "4–6 hrs" },
      { id: "s18", name: "Move-in/out Clean", description: "Full property clean", price: 200, unit: "per session", duration: "5–7 hrs" },
    ],
    createdAt: "2023-08-22",
  },
  {
    id: "prov_6",
    userId: "user_15",
    businessName: "ProPaint NYC",
    categoryId: "cat_6",
    categoryName: "Painting",
    location: "Staten Island, New York",
    rating: 4.4,
    reviewCount: 67,
    verified: true,
    bio: "Interior and exterior painting specialists. Quality finishes, on-time delivery. Free estimates.",
    experience: "12 years",
    availability: "Mon–Fri, 8am–6pm",
    phone: "+1 (555) 100-2006",
    email: "propaint@example.com",
    images: [],
    services: [
      { id: "s19", name: "Interior Painting", description: "Walls & ceilings", price: 3, unit: "per sq ft", duration: "varies" },
      { id: "s20", name: "Exterior Painting", description: "House exterior", price: 4, unit: "per sq ft", duration: "varies" },
      { id: "s21", name: "Cabinet Painting", description: "Kitchen cabinets", price: 350, unit: "per set", duration: "2 days" },
    ],
    createdAt: "2023-05-14",
  },
];

// Eight sample reviews spread across the top providers.
// Used during development to preview the reviews section without a live backend.
export const REVIEWS: Review[] = [
  {
    id: "rev_1",
    userId: "user_20",
    userName: "Sarah M.",
    providerId: "prov_1",
    rating: 5,
    comment: "Excellent service! The technician arrived on time, was very professional, and fixed our AC quickly. Highly recommend!",
    createdAt: "2025-04-10",
  },
  {
    id: "rev_2",
    userId: "user_21",
    userName: "James K.",
    providerId: "prov_1",
    rating: 5,
    comment: "Best AC service in the city. Fair pricing and the team cleaned up after themselves. Will use again.",
    createdAt: "2025-03-28",
  },
  {
    id: "rev_3",
    userId: "user_22",
    userName: "Linda R.",
    providerId: "prov_1",
    rating: 4,
    comment: "Good work overall. Took a bit longer than estimated but the result was great.",
    createdAt: "2025-03-15",
  },
  {
    id: "rev_4",
    userId: "user_23",
    userName: "Tom B.",
    providerId: "prov_2",
    rating: 5,
    comment: "Called at midnight for an emergency leak. They came within an hour. Lifesavers!",
    createdAt: "2025-04-05",
  },
  {
    id: "rev_5",
    userId: "user_24",
    userName: "Priya S.",
    providerId: "prov_2",
    rating: 4,
    comment: "Professional and efficient. Fixed the clog quickly at a fair price.",
    createdAt: "2025-03-20",
  },
  {
    id: "rev_6",
    userId: "user_25",
    userName: "Michael O.",
    providerId: "prov_3",
    rating: 5,
    comment: "Spark Electric did an amazing panel upgrade. Everything up to code, very tidy work.",
    createdAt: "2025-04-12",
  },
  {
    id: "rev_7",
    userId: "user_26",
    userName: "Emily H.",
    providerId: "prov_3",
    rating: 5,
    comment: "Installed 6 new outlets for our home office setup. Quick, clean, and priced fairly.",
    createdAt: "2025-04-01",
  },
  {
    id: "rev_8",
    userId: "user_27",
    userName: "Carlos M.",
    providerId: "prov_5",
    rating: 5,
    comment: "The deep clean was incredible. The apartment looks brand new. Worth every penny.",
    createdAt: "2025-04-18",
  },
];

// Three demo user accounts for testing the three distinct roles in the app.
// Any password is accepted by the demo backend for these accounts.
export const DEMO_USERS: User[] = [
  {
    id: "user_1",
    name: "Alice Johnson",
    email: "user@demo.com",
    phone: "+1 (555) 001-0001",
    role: "user",
    createdAt: "2024-06-01",
  },
  {
    id: "user_10",
    name: "Bob Smith",
    // This userId also owns prov_1 (CoolBreeze AC Services) in PROVIDERS
    email: "provider@demo.com",
    phone: "+1 (555) 001-0010",
    role: "provider",
    createdAt: "2023-03-10",
  },
  {
    id: "user_admin",
    name: "Admin User",
    email: "admin@demo.com",
    phone: "+1 (555) 001-0099",
    role: "admin",
    createdAt: "2022-01-01",
  },
];
